import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { formatModifier, getModifier } from '@/lib/types';
import { Link } from 'react-router-dom';
import { HpBar } from './HpBar';
export function CharacterCard({ character }) {
    const strMod = getModifier(character.abilities.find(a => a.name === 'STR')?.score ?? 10);
    const dexMod = getModifier(character.abilities.find(a => a.name === 'DEX')?.score ?? 10);
    return (_jsx(Link, { to: `/character/${character.id}`, children: _jsxs(motion.div, { className: "tactical-card cursor-pointer", whileHover: { borderColor: 'rgba(255,255,255,0.15)' }, whileTap: { scale: 0.98 }, transition: { duration: 0.15 }, children: [_jsxs("div", { className: "flex items-start justify-between mb-3", children: [_jsxs("div", { className: "flex items-center gap-3", children: [character.icon ? (_jsx("img", { src: character.icon, className: "w-10 h-10 rounded-full object-cover border border-border shrink-0", alt: "" })) : (_jsx("div", { className: "w-10 h-10 rounded-full bg-muted flex items-center justify-center shrink-0", children: _jsx("span", { className: "font-mono text-sm text-muted-foreground", children: character.name[0] }) })), _jsxs("div", { children: [_jsx("h3", { className: "font-display text-base text-foreground", children: character.name }), _jsxs("p", { className: "text-[11px] text-muted-foreground uppercase tracking-widest", children: ["LVL ", character.level, " ", character.race, " ", character.class] })] })] }), _jsxs("div", { className: "text-right", children: [_jsx("span", { className: "font-mono text-2xl tabular-nums text-foreground", children: character.ac }), _jsx("p", { className: "stat-label", children: "AC" })] })] }), _jsx(HpBar, { current: character.hp, max: character.maxHp }), _jsxs("div", { className: "flex gap-4 mt-3", children: [_jsxs("div", { className: "text-center", children: [_jsx("span", { className: "font-mono text-sm tabular-nums", children: formatModifier(character.abilities.find(a => a.name === 'STR')?.score ?? 10) }), _jsx("p", { className: "stat-label", children: "STR" })] }), _jsxs("div", { className: "text-center", children: [_jsx("span", { className: "font-mono text-sm tabular-nums", children: formatModifier(character.abilities.find(a => a.name === 'DEX')?.score ?? 10) }), _jsx("p", { className: "stat-label", children: "DEX" })] }), _jsxs("div", { className: "text-center", children: [_jsxs("span", { className: "font-mono text-sm tabular-nums", children: [character.speed, " ft"] }), _jsx("p", { className: "stat-label", children: "SPD" })] }), _jsxs("div", { className: "text-center", children: [_jsx("span", { className: "font-mono text-sm tabular-nums", children: character.equipment.length }), _jsx("p", { className: "stat-label", children: "ITEMS" })] })] })] }) }));
}
