import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { HashRouter, Route, Routes } from "react-router-dom";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppSidebar } from "@/components/AppSidebar";
import { DiceFloatingButton } from "@/components/DiceFloatingButton";
import { GameProvider } from "@/lib/GameContext";
import Index from "./pages/Index";
import CreateCharacter from "./pages/CreateCharacter";
import CharacterView from "./pages/CharacterView";
import Resources from "./pages/Resources";
import DiceRoller from "./pages/DiceRoller";
import Maps from "./pages/Maps";
import NotFound from "./pages/NotFound";
const queryClient = new QueryClient();
const App = () => (_jsx(QueryClientProvider, { client: queryClient, children: _jsx(TooltipProvider, { children: _jsxs(GameProvider, { children: [_jsx(Toaster, {}), _jsx(Sonner, {}), _jsx(HashRouter, { children: _jsxs("div", { className: "flex min-h-screen bg-background", children: [_jsx(AppSidebar, {}), _jsx("main", { className: "flex-1 min-w-0 pt-12 md:pt-0", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Index, {}) }), _jsx(Route, { path: "/create", element: _jsx(CreateCharacter, {}) }), _jsx(Route, { path: "/character/:id", element: _jsx(CharacterView, {}) }), _jsx(Route, { path: "/resources", element: _jsx(Resources, {}) }), _jsx(Route, { path: "/dice", element: _jsx(DiceRoller, {}) }), _jsx(Route, { path: "/maps", element: _jsx(Maps, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }) }), _jsx(DiceFloatingButton, {})] }) })] }) }) }));
export default App;
